modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="getinthebucketmod"
version="4.0.0a"
displayName="Get in the Bucket Mod"
logoFile="logo.png"
authors="Vladyslav Aviedov"
description='''
Mod that allows you to put mobs into buckets
'''

# Forge
[[dependencies.getinthebucketmod]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.getinthebucketmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
