modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="getinthebucketmod"
version="4.1.2"
displayName="Get in the Bucket Mod"
logoFile="logo.png"
authors="Vladyslav Aviedov"
description='''
Mod that allows you to put mobs into buckets
'''

# Forge
[[dependencies.getinthebucketmod]]
    modId="forge"
    mandatory=true
    versionRange="[41.1,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.getinthebucketmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
