modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="getinthebucketmod"

# Display
version="${file.jarVersion}"
displayName="Get in the Bucket Mod"
logoFile="logo.png"

# Authors etc
credits="myself"
authors="Vladyslav Aviedov"
description='''
Get in the Bucket Mod
'''

# Forge
[[dependencies.getinthebucketmod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.getinthebucketmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
