modLoader="javafml"
loaderVersion="46.0.10"
license="MIT"

[[mods]]
modId="gitbm"
version="4.2.0"
displayName="Get in the Bucket Mod"
logoFile="logo.png"
authors="Vladyslav Aviedov"
description='''
Mod that allows you to put mobs into buckets
'''

# Forge
[[dependencies.gitbm]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.10,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.gitbm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
