name: Java CI with Gradle

on:
  push:
    branches: [ 17a ]
  pull_request:
    branches: [ 17a ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: gradle
    - name: Regular Build
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build -x spotlessJavaCheck

  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: gradle
    - name: Code Quality Check
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: spotlessJavaCheck
